services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: testwork_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "80:8000"
    depends_on:
      - db
     command: sh -c "[ -f vendor/autoload.php ] || composer install --no-interaction --prefer-dist && php artisan serve --host=0.0.0.0 --port=8000"

  front:
    build:
    user: "${UID:-1000}:${GID:-1000}"    
      context: .
      dockerfile: Dockerfile.front
    container_name: testwork_front
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "5173:5173"
    command: sleep infinity

  db:
    image: postgres:17
    container_name: testwork_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-testwork}
      POSTGRES_USER: ${DB_USERNAME:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
